### ISSUE TITLE
Variable reading error, misspelling

### ISSUE THREAD

**Issue by rishumon** [wuori/vue-cardswipe#12]
https://github.com/wuori/vue-cardswipe/blob/1a956daee5e1ed4518d401d284f5afd855e53ff1/src/cardswipe.js#L251
Seems like a typo
Calling the swipeData variable should be corrected instead
To cardSwipe

**Comment by wuori** [comment]
@rishumon I think you're right, I'll try to get the change up soon. I'm on a new machine and will take a bit to build/test.
